### ISSUE TITLE
Final Decomposition and Style Check Before Finish Baseline Milestone

### ISSUE THREAD

**Issue by solbarth** [zoesol/furry-telegram#15]
- [x] Home Page
- [x] Add Habit Page
- [x] Habit 
- [x] Goals Page
- [x] Add Goal Page
- [x] Long Term Goal
